spring.application.name=urlshortener
server.port=8081

# Configuração MongoDB
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=shortenerdb
spring.data.mongodb.username=admin
spring.data.mongodb.password=123
# Secret key do hashid - Garante que os HashIDs sejam �nicos e imprevis�veis
hashids.salt=A-R-aNd0m-PhR4s3-With_Symbol5_AnD-NuMb3r5_T0_M4k3_It_Str0nG_G_G

# Configuração do Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

# Configuração da página de boas-vindas
spring.web.resources.static-locations=classpath:/templates/,classpath:/static/,classpath:/public/
spring.mvc.static-path-pattern=/static/**
